In [17]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [18]:
a = np.array(range(5))+1
print a[0:]

[1 2 3 4 5]


In [19]:
print a[:0]

[]


In [27]:
b = np.ceil(np.random.rand(3)*100)
print b

[ 26.  97.  46.]


In [29]:
d = np.concatenate((b, a[:-3]), axis=0)
print d

[ 26.  97.  46.   1.   2.]


In [22]:
print 25**2-7**2

576


In [25]:
576**.5


24.0

In [9]:
print a[:-2]

[1 2 3 4 5 6 7 8]
