In [194]:
# %load gen.py
import numpy as np
import scipy
import aipy
import linsolve
import collections
import Combinatorics


In [2]:
import numpy as np
import scipy
import aipy
import linsolve
import collections


In [4]:
# antdict = {}
# antlist = {}
# sigdict = {}
# for i in range(antcount):
#     key = 'ant'+str(i+1)
#     antdict[key] = []
#     for k in range(sigcount):
#         antdict[key].append('sig' + str(i+1) + '_' + str(k+1))
# print antdict

In [169]:
# def dmul(sigcount, dt=0, mode='wcon'):
#     assert (a.shape[1]>0) #dmul only works for array of arrays
#     assert mode in ('wcon' , 'rand' , 'wfft')
antcount = 3 # Antenna Count
sigcount = 2 # signal count 
datasize = 3 # data size of each signal
coords = 3 # one-dim, two-dim , or three-dim
signals = np.random.rand(sigcount, datasize) # Signal list
minbase = np.array([np.random.randn(), 0, 0]) # One-dimensional antenna array 
clk_pr = 5 # ns
siglocs = np.random.rand(sigcount, coords) #Signal locations
delist = [] # Delay list
gains = [] # Gain list
print len(delist)

0


In [170]:
if len(delist)==0:
    for i in range(sigcount):
        # delay of each signal based on their location in the sky
        delist.append(np.dot(minbase, siglocs[i]) / aipy.const.len_ns / clk_pr)

In [171]:
if len(gains)==0:
    for i in range(antcount):
        gains.append(np.random.uniform(.5,1.5))

print len(delist)
print delist
print len(gains)
print gains

# np.put(delarray, [0], [0])
# for i in range(len(delist)):
#     print delist[i]==delarray[i]
# print gainarray

2
[0.0004032586242996089, 0.0028903304959892262]
3
[0.721042051159196, 1.0123942945254187, 0.6914409948488732]


In [178]:
f_fft=np.fft.fft(signals)
nu = np.fft.fftfreq(datasize)
delsig = []
if len(delsig)==0:
    for i in range(sigcount):
        dt = delist[i]
        for k in range(antcount):
            phi = np.exp(-2j*np.pi*nu*dt*k)
            fcvp = np.fft.ifft(phi*f_fft)
            delsig.append(fcvp.real[i])
            delsigarray = np.array(delsig)
print delsig,'\n', delsigarray

[array([ 0.74791599,  0.38749347,  0.86959461]), array([ 0.74815105,  0.38743424,  0.86941879]), array([ 0.74838605,  0.3873752 ,  0.86924283]), array([ 0.62611602,  0.03902845,  0.49859851]), array([ 0.62771784,  0.03948051,  0.49654463]), array([ 0.62931087,  0.03994534,  0.49448677])] 
[[ 0.74791599  0.38749347  0.86959461]
 [ 0.74815105  0.38743424  0.86941879]
 [ 0.74838605  0.3873752   0.86924283]
 [ 0.62611602  0.03902845  0.49859851]
 [ 0.62771784  0.03948051  0.49654463]
 [ 0.62931087  0.03994534  0.49448677]]


In [193]:
antsig = []
# print 'delsig\n', delsig
for i in range(antcount):
#     print 'delsig \n' ,np.sum(delsig[i::antcount], axis=0)
#     print 'delsigarray\n' ,np.sum(delsigarray[i::antcount], axis =0)
    antsig.append(np.sum(delsigarray[i::antcount], axis =0))
# print a,'\n\n', antsig
# print gains
# print a
measig = []
for i in range(antcount):
    measig.append(gains[i]*antsig[i])
print measig

[array([ 0.99073486,  0.30754024,  0.98652478]), array([ 1.39292181,  0.43220605,  1.38289358]), array([ 0.95259612,  0.29546694,  0.94293855])]


In [192]:
f_fft = np.fft.fft(measig)

print f_fft
# print f_fft.shape
# for i in range(antcount):
#     if i+1< antcount:
#         f_fft[i]*f_fft[i+1]

[[ 2.28479988+0.j          0.34370236+0.58801786j  0.34370236-0.58801786j]
 [ 3.20802144+0.j          0.48537200+0.82331954j  0.48537200-0.82331954j]
 [ 2.19100162+0.j          0.33339338+0.56072686j  0.33339338-0.56072686j]]


In [184]:
comb = list(m_way_unordered_combinations(antcount,[2]))
# print len(comb)

# print comb[2][0][1]
# print comb
comblist = []
for i in range(len(comb)):
    comblist.append(comb[i][0])
pairs = []
for i in range(len(comb)):
    pairs.append(comb[i][0][0])
    pairs.append(comb[i][0][1])
    pairsarr = np.array(pairs)
print pairs
print pairsarr.size

[0, 1, 0, 2, 1, 2]
6


In [187]:
print measig
for i in range(pairsarr.size/2):
    print measig[pairs[i*2]]*measig[pairs[2*i+1]]


[array([ 0.99073486,  0.30754024,  0.98652478]), array([ 1.39292181,  0.43220605,  1.38289358]), array([ 0.95259612,  0.29546694,  0.94293855])]
[ 1.3800162   0.13292075  1.36425877]
[ 0.94377019  0.09086797  0.93023224]
[ 1.32689192  0.1277026   1.30398366]


In [62]:
delsigfft = np.fft.rfft(delsigarray)
delsigconj = delsigfft.conj()

# for i in range(sigcount*antcount):
    

In [6]:
test1 = []

for i in range(4):
    test1.insert(i, 'ant' + str(i))
    
print test1[0]

ant0


In [7]:
test = {}
antcount = 4
sigcount = 2
for i in range(antcount):
    for k in range(sigcount):
        test['ant'+str(i+1)+str(k)] = str(i) + str(k)

In [8]:
for key,val, in test.items():
    print key, '=====>', val

ant31 =====> 21
ant30 =====> 20
ant11 =====> 01
ant10 =====> 00
ant40 =====> 30
ant41 =====> 31
ant20 =====> 10
ant21 =====> 11


In [9]:
# print collections.OrderedDict(sorted(test.items()))
# print test.keys()[0:3]
l = ['12!', '!', '21']
for i in range(len(l)):
    if '2!' in l[i]:
        print 'true'
    
    else:
        print 'false'

true
false
false


In [10]:
test = {}
test[(1,2,'xx')] = np.arange(10)
test[(1,'x')] = 'stuff'
test['string'] = 1

print test['string']
print test.values()
print test.keys()
print test.items()
for key,val, in test.items():
    print key, '=====>', val

test2 = {}
for i in range(10):
    test2[str(2*i)] = i

print test2.items()

1
[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'stuff', 1]
[(1, 2, 'xx'), (1, 'x'), 'string']
[((1, 2, 'xx'), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])), ((1, 'x'), 'stuff'), ('string', 1)]
(1, 2, 'xx') =====> [0 1 2 3 4 5 6 7 8 9]
(1, 'x') =====> stuff
string =====> 1
[('10', 5), ('12', 6), ('14', 7), ('16', 8), ('18', 9), ('0', 0), ('2', 1), ('4', 2), ('6', 3), ('8', 4)]
